### ISSUE TITLE
FlyCaptureCamera fails to configure

### ISSUE THREAD

**Issue by w-figtree-neura** [w-figtree-neura/StableEyesV4#1]
After a physical disconnect, FlyCaptureCamera often fails in the configure step. Sometimes this prevents further usage, sometimes it doesn't.

The exception thrown is:

FlyCapture2Managed.FC2Exception: Generation count is incorrect.
   at FlyCapture2Managed.ManagedCameraBase.GetConfiguration()
   at SE.Core.Components.Camera.FC.FlyCaptureCamera.Configure(Object config) in C:\Users\Will\Documents\stableeyes4B\Desktop Application\SE.Core\Components\Camera\FlyCapture\FlyCaptureCamera.cs:line 119

The inner exception comes from the FlyCapture C libraries...
Error Trace:
Source: IidcCameraInternal.cpp(658) Built: Jan  9 2018 22:31:20 - Generation count is incorrect.
+-> From: CameraInternal.cpp(113) Built: Jan  9 2018 22:31:19 - Generation count is incorrect.

**Comment by w-figtree-neura** [comment]
Whoops this is the old repo. Copied this issue to the new repo.
