### ISSUE TITLE
SerialController throws an unobserved exception on connection after physical disconnect

### ISSUE THREAD

**Issue by w-figtree-neura** [w-figtree-neura/StableEyesV4#2]
Need to implement better management of the listener thread in SerialController. At the moment it isn't tracked and can result in weird exceptions. These exceptions are expected from a physical disconnect but should be handled better. They indicate a broader issue with this set and forget style listener.

THE EXCEPTION THROWN AFTER DISCONNECT
2019-07-29 14:50:42,036 [4] ERROR SerialController Serial port read error.
System.IO.IOException: The I/O operation has been aborted because of either a thread exit or an application request.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SE.Core.Components.Controller.SerialController.<ListenAsync>d__47.MoveNext() in C:\Users\Will\Documents\stableeyes4B\Desktop Application\SE.Core\Components\Controller\SerialController.cs:line 451

THE UNOBSERVED EXCEPTION:
2019-07-29 14:46:05,413 [2] ERROR App Unobserved exception thrown by [System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.TaskExtensions+VoidResult]].
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: The port is closed.
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SE.Core.Components.Controller.SerialController.<ListenAsync>d__47.MoveNext() in C:\Users\Will\Documents\stableeyes4B\Desktop Application\SE.Core\Components\Controller\SerialController.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SE.Core.Components.Controller.SerialController.<<ConnectAsync>b__43_0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The port is closed.
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SE.Core.Components.Controller.SerialController.<ListenAsync>d__47.MoveNext() in C:\Users\Will\Documents\stableeyes4B\Desktop Application\SE.Core\Components\Controller\SerialController.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SE.Core.Components.Controller.SerialController.<<ConnectAsync>b__43_0>d.MoveNext()<---

**Comment by w-figtree-neura** [comment]
Whoops this is the old repo. Copied this issue to the new repo.
